"""AE Handoff — Claude managed agent (Claude Agent SDK).

The agent's logic lives in SYSTEM_PROMPT (mirrors agents/operations/ae-handoff.md).
Custom tools wrap your stack: query_crm, search_calls, send_slack_message. Claude reconstructs
the deal from CRM facts + its calls, writes the handoff, then posts it to the delivery/CS channel.

There are two Claude paths:
  - THIS file: the in-process Claude Agent SDK (`pip install claude-agent-sdk`). You run it on a
    schedule (cron / APScheduler), or trigger it from a CRM Closed-Won webhook. Custom tools are
    registered via an in-process MCP server.
  - Hosted alternative: the Managed Agents API (`anthropic` SDK, `client.beta.agents.create` +
    sessions) for Anthropic-hosted sessions you invoke from cron. Use that if you don't want a
    long-running process. Either way, paste SYSTEM_PROMPT and wire the same three tools.

Verify against the current SDK (version-sensitive): import paths and the @tool / query surface.
Fill the CRM / recorder / Slack calls marked TODO with your real APIs.
"""
import asyncio

from claude_agent_sdk import ClaudeAgentOptions, create_sdk_mcp_server, query, tool

SYSTEM_PROMPT = """You are the AE Handoff agent. On each run:
1. Use query_crm to list every opportunity that reached Closed-Won since the last run (name, account,
   amount, term, close date, AE owner, CSM owner, primary contact, opportunity team, products/line
   items, and custom fields like implementation tier, region, segment). If none, send a Slack note
   that no deals reached Closed-Won, then stop.
2. For each won deal, use search_calls to pull the calls tied to the opportunity (fall back to the
   account) and reconstruct the timeline.
3. Extract from those calls: participants and roles, customer goals and pain points, decisions and AE
   commitments, technical details and integrations, and any timelines, blockers, or risks. If
   conversation data is missing, add guidance like "review CRM notes" or "schedule a follow-up with AE."
4. Write the handoff with these emoji section headers, in order: :tada: NEW CLOSED WON HANDOFF,
   :receipt: DEAL OVERVIEW, :busts_in_silhouette: KEY STAKEHOLDERS (Champion, Decision Maker,
   Technical Contact, AE, Implementation Lead with names + titles), :dart: GOALS AND SUCCESS CRITERIA,
   :jigsaw: SCOPE AND INTEGRATIONS, :handshake: COMMITMENTS OR SPECIAL TERMS, :warning: RISKS AND
   WATCHOUTS, :rocket: NEXT STEPS (3-5 kickoff actions with owners + dates), :paperclip: RESOURCES
   (links to the CRM opp, linked calls, proposal/SOW). End with a footer: "Generated by GTM
   Superintelligence | Opportunity ID: [ID] | [Date and Time UTC]". Mention the AE and CSM.
5. Post the handoff with send_slack_message to the delivery/CS channel.
Tie every claim to CRM data or a call quote. Humanizer rules on the message: no em dashes, no AI
throat-clearing, no hype adjectives, one clear ask."""


@tool("query_crm", "Read CRM opportunities. Use to list Closed-Won deals and their fields.", {"soql_or_filter": str})
async def query_crm(args):
    # TODO: call your CRM (Salesforce/HubSpot/...) and return the matching Closed-Won opportunities.
    raise NotImplementedError("Wire to your CRM API")


@tool("search_calls", "Find the calls/transcripts tied to a deal or account.", {"deal_or_account": str})
async def search_calls(args):
    # TODO: call your recorder's API, or load transcripts via the dealtrace adapters (load_transcript).
    raise NotImplementedError("Wire to your call recorder / dealtrace adapters")


@tool("send_slack_message", "Post the handoff to a Slack channel.", {"channel": str, "text": str})
async def send_slack_message(args):
    # TODO: post to Slack (Web API or webhook).
    raise NotImplementedError("Wire to Slack")


async def run_once():
    tools = create_sdk_mcp_server(name="gtm_tools", version="1.0.0",
                                  tools=[query_crm, search_calls, send_slack_message])
    options = ClaudeAgentOptions(
        system_prompt=SYSTEM_PROMPT,
        mcp_servers={"gtm_tools": tools},
        allowed_tools=[
            "mcp__gtm_tools__query_crm",
            "mcp__gtm_tools__search_calls",
            "mcp__gtm_tools__send_slack_message",
        ],
        permission_mode="acceptEdits",
    )
    async for _ in query(prompt="Find any deals that just reached Closed-Won and post their handoffs.", options=options):
        pass


if __name__ == "__main__":
    # Schedule externally, e.g. cron:  0 * * * *  python claude-agent.py
    # Better: trigger from your CRM's Closed-Won stage-change webhook.
    asyncio.run(run_once())
