"""AE Handoff — LangGraph build.

A 4-node graph: fetch Closed-Won deals -> fetch their calls -> Claude writes the handoff -> post to
Slack. Swap the TODO bodies for your CRM / recorder / Slack. The reasoning is one Anthropic call whose
system prompt is the agent's operating logic (mirrors agents/operations/ae-handoff.md).

    pip install langgraph anthropic
    export ANTHROPIC_API_KEY=...
    python langgraph.py        # or call build_graph().invoke({}) from your scheduler (cron, Airflow, ...)
"""
from __future__ import annotations

from typing import Any, TypedDict

import anthropic
from langgraph.graph import END, START, StateGraph

SYSTEM_PROMPT = """You are the AE Handoff agent. Given the Closed-Won deals and their calls, write a
handoff for the delivery/CS team. Reconstruct each deal from its calls: participants and roles,
customer goals and pain points, AE commitments, technical details and integrations, timelines,
blockers, and risks. Write the handoff with these emoji section headers in order: :tada: NEW CLOSED
WON HANDOFF, :receipt: DEAL OVERVIEW, :busts_in_silhouette: KEY STAKEHOLDERS (Champion, Decision
Maker, Technical Contact, AE, Implementation Lead with names + titles), :dart: GOALS AND SUCCESS
CRITERIA, :jigsaw: SCOPE AND INTEGRATIONS, :handshake: COMMITMENTS OR SPECIAL TERMS, :warning: RISKS
AND WATCHOUTS, :rocket: NEXT STEPS (3-5 kickoff actions with owners + dates), :paperclip: RESOURCES.
End with the footer: "Generated by GTM Superintelligence | Opportunity ID: [ID] | [Date and Time UTC]".
Mention the AE and CSM. Tie every claim to CRM data or a call quote. Humanizer rules: no em dashes, no
AI throat-clearing, no hype, one clear ask. Output the handoff exactly per the canonical spec."""


class State(TypedDict, total=False):
    deals: list[dict[str, Any]]
    calls: list[dict[str, Any]]
    report: str


def fetch_won_deals(state: State) -> State:
    # TODO: query your CRM for Closed-Won opportunities in the window (with their fields).
    return {"deals": []}


def fetch_calls(state: State) -> State:
    # TODO: for each deal, fetch its calls from your recorder, or load transcripts via the
    # dealtrace adapters: from dealtrace.adapters import load_transcript
    return {"calls": []}


def analyze(state: State) -> State:
    if not state.get("deals"):
        return {"report": "AE Handoff ran. No deals reached Closed-Won."}
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=3000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": f"WON DEALS:\n{state['deals']}\n\nCALLS:\n{state.get('calls', [])}"}],
    )
    return {"report": msg.content[0].text}


def post_report(state: State) -> State:
    # TODO: post state["report"] to your delivery/CS Slack channel (Web API or webhook).
    print(state["report"])
    return {}


def build_graph():
    g = StateGraph(State)
    g.add_node("fetch_won_deals", fetch_won_deals)
    g.add_node("fetch_calls", fetch_calls)
    g.add_node("analyze", analyze)
    g.add_node("post_report", post_report)
    g.add_edge(START, "fetch_won_deals")
    g.add_edge("fetch_won_deals", "fetch_calls")
    g.add_edge("fetch_calls", "analyze")
    g.add_edge("analyze", "post_report")
    g.add_edge("post_report", END)
    return g.compile()


if __name__ == "__main__":
    build_graph().invoke({})
