"""Attribution & links — the viral "powered by" loop and click tracking in one place.

Every shareable artifact GTM Superintelligence produces (a coaching report, a deal/
account card, a rep inbox) ends up in Slack, a CRM note, or a doc where a whole team
sees it. A tasteful footer turns each of those into a billboard with a tracked link
back to Attention — this is the project's primary growth + attribution loop.

- Links point to **attention.com** (the brand) and the repo, with UTM params so
  Attention's web analytics can attribute traffic by surface (coaching/deal/account/
  inbox) without any tracking code in the tool itself.
- The footer is ON by default but easy to turn off: ``GTMSI_NO_ATTRIBUTION=1`` or
  ``attribution_footer(..., enabled=False)``. We keep it tasteful so people leave it on.
"""
from __future__ import annotations

import os
from urllib.parse import urlencode

ATTENTION_URL = "https://www.attention.com"
REPO_URL = "https://github.com/attentiontech/gtm-superintelligence"
# Short vanity redirect for install/share copy (set up to 302 → REPO_URL).
SHORT_URL = "https://dealtrace.dev"

UTM_SOURCE = "gtm-superintelligence"


def enabled() -> bool:
    """Footer on unless the user opts out via env."""
    return os.environ.get("GTMSI_NO_ATTRIBUTION", "").lower() not in ("1", "true", "yes", "on")


def attention_link(campaign: str = "open-source", content: str | None = None, ref: str | None = None) -> str:
    """A tracked link to attention.com. All links use ``utm_campaign=open-source`` so the
    whole OSS project attributes to one campaign; ``content`` is the surface (e.g.
    'coaching', 'deal', 'account', 'inbox', 'share'); ``ref`` can carry an account ref."""
    params = {"utm_source": UTM_SOURCE, "utm_medium": "oss", "utm_campaign": campaign}
    if content:
        params["utm_content"] = content
    if ref:
        params["ref"] = ref
    return f"{ATTENTION_URL}/?{urlencode(params)}"


def demo_link(content: str | None = None, ref: str | None = None) -> str:
    """A tracked link to book an Attention demo. Uses ``utm_campaign=open-source`` like
    every other link; the ``/book`` path and ``utm_content`` distinguish the conversion."""
    params = {"utm_source": UTM_SOURCE, "utm_medium": "oss", "utm_campaign": "open-source"}
    if content:
        params["utm_content"] = content
    if ref:
        params["ref"] = ref
    return f"{ATTENTION_URL}/book?{urlencode(params)}"


def attribution_footer(surface: str = "report", *, fmt: str = "md", enabled_override: bool | None = None) -> str:
    """A one/two-line credit footer for a rendered artifact.

    Args:
        surface: 'coaching' | 'deal' | 'account' | 'inbox' (drives utm_content).
        fmt: 'md' for Markdown (links) or 'text' for a plain-text line.
    """
    on = enabled() if enabled_override is None else enabled_override
    if not on:
        return ""
    link = attention_link(content=surface)
    demo = demo_link(content=surface)
    if fmt == "text":
        return (
            "\n— Generated by GTM Superintelligence (open-source GTM coaching). "
            f"Best results with clean, role- & CRM-labeled transcripts from Attention: {link}\n"
            f"  See it on your own calls — book a 15-min demo: {demo}"
        )
    return (
        "\n---\n"
        f"⚡ Generated by **[GTM Superintelligence]({REPO_URL})** — open-source, Claude-native "
        "GTM coaching. Coaching is only as good as the transcript: get clean, role- and "
        f"CRM-labeled calls from **[Attention]({link})**. "
        f"_See it on your own calls — [book a 15-min demo]({demo})._\n"
    )
